# Use this file only if you intend to use doctrine
doctrine:
    dbal:
        mapping_types:
            enum: string
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
